# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt-tech-fech.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pandas as pd



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(892, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 900, 700))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")



        self.carsButton = QtWidgets.QPushButton(self.tab)
        self.carsButton.setGeometry(QtCore.QRect(0, 190, 101, 41))
        self.carsButton.setObjectName("carsButton")
        self.customersButton = QtWidgets.QPushButton(self.tab)
        self.customersButton.setGeometry(QtCore.QRect(0, 260, 101, 41))
        self.customersButton.setObjectName("customersButton")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 450, 900, 201))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tabWidget_2.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.tabWidget_2.addTab(self.tab_12, "")

        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(120, 30, 731, 401))
        self.tableWidget.setObjectName("tableWidget")
        # self.tableWidget.setColumnCount(0)
        # self.tableWidget.setRowCount(0)
        self.tabWidget.addTab(self.tab, "")

        self.warehouseButton = QtWidgets.QPushButton(self.tab)
        self.warehouseButton.setGeometry(QtCore.QRect(0, 120, 101, 41))
        self.warehouseButton.setObjectName("warehouseButton")

        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.warehouseButton.clicked.connect(self.loadExcelDatas)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)





    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.warehouseButton.setText(_translate("MainWindow", "Kho"))
        self.carsButton.setText(_translate("MainWindow", "Đội xe"))
        self.customersButton.setText(_translate("MainWindow", "Khách hàng"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), _translate("MainWindow", "Tab 1"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_12), _translate("MainWindow", "Tab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Help"))


    def loadExcelDatas(self):
        df = pd.read_excel(excel_file_path)
        # print(df.shape[0])
        # print(df.shape[1])
        # print(df.head())

        if df.size == 0:
            return

        self.tableWidget.setRowCount(df.shape[0])
        self.tableWidget.setColumnCount(df.shape[1])
        self.tableWidget.setHorizontalHeaderLabels(df.columns)

        for row in df.iterrows():
            print(row)
            values = row[1];
            for col_index,value in enumerate(values):
                # if isinstance(value, (float,int )):
                    # value = '{0:0,.0f}'.format(value)
                tableItem =  QtWidgets.QTableWidgetItem(str(value))
                self.tableWidget.setItem(row[0],col_index, tableItem)





if __name__ == "__main__":
    import sys
    excel_file_path = 'testExcel.xlsx'
    worksheet_name = 'Sheet1'
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
